import { chromium } from 'playwright';
const exe = 'C:/Users/Dexin/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe';
const browser = await chromium.launch({ executablePath: exe });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5177/', { waitUntil: 'networkidle' });
await page.waitForTimeout(200);
await page.screenshot({ path: 'assets/raw/_h0.png' });
await page.waitForTimeout(3500);
await page.screenshot({ path: 'assets/raw/_h1.png' });
await browser.close();
